name: mapbox_maps_flutter
description: Interactive, thoroughly customizable maps powered by Mapbox Maps mobile SDKs.
version: 2.5.0
homepage: https://github.com/mapbox/mapbox-maps-flutter

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.22.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.23
  turf: ^0.0.8
  typed_data: ^1.3.0
  meta: ^1.15.0
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  http: 1.2.2


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  flutter_lints: ^5.0.0
  pigeon: ^22.6.1
  permission_handler: ^11.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.maps.mapbox_maps
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
  assets:
    - lib/assets/icons/navigation/svg/